# Generated by Django 4.0.3 on 2022-03-31 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RLSPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_object_id', models.CharField(max_length=36, verbose_name='object id')),
                ('grantee_object_id', models.CharField(max_length=36, verbose_name='grantee id')),
                ('grantee_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rls_permitted', to='contenttypes.contenttype', verbose_name='grantee content type')),
                ('record_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rls_permissions', to='contenttypes.contenttype', verbose_name='record content type')),
            ],
            options={
                'verbose_name': 'Record Level Security permission',
                'verbose_name_plural': 'Record Level Security permissions',
            },
        ),
        migrations.AddConstraint(
            model_name='rlspermission',
            constraint=models.UniqueConstraint(fields=('record_content_type', 'record_object_id', 'grantee_content_type', 'grantee_object_id'), name='unique record and grantee'),
        ),
    ]
