# Generated by Django 4.0.3 on 2022-04-08 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('djangoRLS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rlspermission',
            name='permit_all',
            field=models.BooleanField(blank=True, default=False, verbose_name='permit all'),
        ),
        migrations.AlterField(
            model_name='rlspermission',
            name='grantee_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rls_permitted', to='contenttypes.contenttype', verbose_name='grantee content type'),
        ),
        migrations.AlterField(
            model_name='rlspermission',
            name='grantee_object_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='grantee id'),
        ),
    ]
